version: '3'
services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest  # 무료 Oracle XE 버전
    container_name: oracle-db
    environment:
      - ORACLE_PWD=1234  # 원하는 비밀번호로 설정
    ports:
      - "1521:1521"  # Oracle DB 접속 포트
      - "5500:5500"  # Oracle Enterprise Manager 포트
    volumes:
      - oracle-data:/opt/oracle/oradata  # 데이터 디렉토리 설정
    networks:
      - oracle-net

volumes:
  oracle-data:

networks:
  oracle-net:
    driver: bridge
